language: generic
sudo: required
services: 
    - docker
before_install:
    - docker build -t utkarshsahu/multicontainer-docker -f ./client/Dockerfile.dev ./client
scripts:
    - docker run -e CI=true utkarshsahu/multicontainer-docker npm run test 
after_success:
    - docker build -t utkarshsahu/multi-client ./client
    - docker build -t utkarshsahu/multi-nginx ./nginx
    - docker build -t utkarshsahu/multi-server ./server
    - docker build -t utkarshsahu/multi-worker ./worker
    - echo "$DOCKER_PASSWORD"| docker login -u "$DOCKER_ID" --password-stdin
    - docker push utkarshsahu/multi-client
    - docker push utkarshsahu/multi-nginx
    - docker push utkarshsahu/multi-server
    - docker push utkarshsahu/multi-worker

